workspace(name = "<%= title %>")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# cpp dependencies

http_archive(
    name = "gtest",
    sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
    strip_prefix = "googletest-release-1.10.0",
    url = "https://github.com/google/googletest/archive/release-1.10.0.zip",
)

# helpers

http_archive(
    name = "com_grail_bazel_compdb",
    sha256 = "bcecfd622c4ef272fd4ba42726a52e140b961c4eac23025f18b346c968a8cfb4",
    strip_prefix = "bazel-compilation-database-0.4.5",
    urls = ["https://github.com/grailbio/bazel-compilation-database/archive/0.4.5.tar.gz"],
)
